# Generated by Django 4.0.5 on 2023-03-31 16:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='costing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=128)),
                ('amount', models.FloatField()),
                ('comments', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('head', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('internal', 'internal'), ('subcontractor', 'subcontractor')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=512)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='open_po',
            fields=[
                ('iwo', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('open_quantity', models.IntegerField()),
                ('closed_quantity', models.IntegerField()),
                ('qc_comments', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('material_group', models.CharField(max_length=100)),
                ('part_num', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled', models.DateField()),
                ('completed', models.DateField()),
                ('cost', models.FloatField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.open_po')),
            ],
        ),
        migrations.CreateModel(
            name='requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inventory')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.open_po')),
            ],
        ),
        migrations.CreateModel(
            name='order_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.open_po')),
            ],
        ),
        migrations.AddField(
            model_name='open_po',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
        migrations.CreateModel(
            name='ipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('quantity', models.IntegerField()),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(default='', max_length=320)),
                ('name', models.CharField(default='', max_length=150)),
                ('designation', models.CharField(default='', max_length=250)),
                ('passWrongCount', models.IntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=10)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(to='auth.group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
