# Generated by Django 4.0.5 on 2023-05-03 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_company_remove_product_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.company'),
            preserve_default=False,
        ),
    ]
