# Generated by Django 4.0.5 on 2023-05-03 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_product_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='open_po',
            name='product',
        ),
    ]
