# Generated by Django 4.0.5 on 2023-05-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_product_uuid_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='part_num',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
