# Generated by Django 4.0.5 on 2023-05-03 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_product_id_alter_product_part_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='open_po',
            name='product',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='api.product'),
            preserve_default=False,
        ),
    ]
