# Generated by Django 4.0.5 on 2023-05-03 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_open_po_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='route',
        ),
    ]
