# Generated by Django 4.0.5 on 2023-05-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_product_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='route',
            field=models.ManyToManyField(to='api.department'),
        ),
    ]
