# Generated by Django 4.0.5 on 2023-05-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_benchmarks_benchmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_status',
            name='completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order_status',
            name='scheduled',
            field=models.DateTimeField(),
        ),
    ]
