version: '3.9'
services:

  erp_db: 
    # UPON DEPLOYMENT: restart: always
    image: postgres
    env_file:
      - ./.env
    environment:
      POSTGRES_HOST: "localhost"
    expose:
      - 5433
    ports:
      - 5433:5432 
    volumes:
      - erp_data:/var/lib/postgresql/data

volumes:
  erp_data:


